---
apiVersion: v1
kind: Namespace
metadata:
  name: lab1
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab2
---
apiVersion: v1
kind: Pod
metadata:
  name: lab
  namespace: lab1
spec:
  containers:
    - name: lab
      image: busybox:1.34.1
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: lab
  namespace: lab2
spec:
  containers:
    - name: lab
      image: busybox:1.34.1
      command: ["sleep", "infinity"]
