---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: getPodsOnly
  namespace: lab1
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: getPodsOnlyBind
  namespace: lab1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: getPodsOnly
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: default
